//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLink
{
    using System;
    using System.Collections.Generic;
    
    public partial class GROUPS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GROUPS()
        {
            this.GROUPS_LECTURES_LINK = new HashSet<GROUPS_LECTURES_LINK>();
            this.GROUPS_MODULES_LINK = new HashSet<GROUPS_MODULES_LINK>();
            this.SEMIGROUPS = new HashSet<SEMIGROUPS>();
        }
    
        public int iID_GROUP { get; set; }
        public string nvNAME { get; set; }
        public int iNUMBER_OF_STUDENTS { get; set; }
        public int iID_GROUP_TYPE { get; set; }
        public int iYEAR { get; set; }
        public bool bACTIVE { get; set; }
        public System.DateTime dtCREATE_DATE { get; set; }
        public Nullable<System.DateTime> dtLASTMODIFIED_DATE { get; set; }
        public int iCREATE_USER { get; set; }
        public Nullable<int> iLASTMODIFIED_USER { get; set; }
    
        public virtual GROUP_TYPES GROUP_TYPES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GROUPS_LECTURES_LINK> GROUPS_LECTURES_LINK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GROUPS_MODULES_LINK> GROUPS_MODULES_LINK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SEMIGROUPS> SEMIGROUPS { get; set; }
    }
}
