//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLink
{
    using System;
    using System.Collections.Generic;
    
    public partial class HALLS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HALLS()
        {
            this.TEACHER_PREFERRED_HALLS = new HashSet<TEACHER_PREFERRED_HALLS>();
        }
    
        public int iID_HALL { get; set; }
        public string nvNAME { get; set; }
        public int iCAPACITY { get; set; }
        public bool bACTIVE { get; set; }
        public System.DateTime dtCREATE_DATE { get; set; }
        public Nullable<System.DateTime> dtLASTMODIFIED_DATE { get; set; }
        public int iCREATE_USER { get; set; }
        public Nullable<int> iLASTMODIFIED_USER { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEACHER_PREFERRED_HALLS> TEACHER_PREFERRED_HALLS { get; set; }
    }
}
