//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLink
{
    using System;
    using System.Collections.Generic;
    
    public partial class PREFERINTE_PROFESORI_SALI
    {
        public int ID_PREFERINTA_PROFESORI_SALI { get; set; }
        public int ID_PROFESOR { get; set; }
        public int ID_SALA { get; set; }
    
        public virtual PROFESORI PROFESORI { get; set; }
        public virtual SALI SALI { get; set; }
    }
}
