//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLink
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEACHERS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TEACHERS()
        {
            this.BLOCKED_MODULES = new HashSet<BLOCKED_MODULES>();
            this.TEACHER_PREFERRED_DAYS = new HashSet<TEACHER_PREFERRED_DAYS>();
            this.TEACHER_PREFERRED_HALLS = new HashSet<TEACHER_PREFERRED_HALLS>();
            this.TEACHER_PREFERRED_MODULES = new HashSet<TEACHER_PREFERRED_MODULES>();
            this.TEACHERS_LECTURES_LINK = new HashSet<TEACHERS_LECTURES_LINK>();
        }
    
        public int iID_TEACHER { get; set; }
        public string nvNAME { get; set; }
        public string nvSURNAME { get; set; }
        public Nullable<bool> bACTIVE { get; set; }
        public Nullable<System.DateTime> dtCREATE_DATE { get; set; }
        public Nullable<System.DateTime> dtLASTMODIFIED_DATE { get; set; }
        public Nullable<int> iCREATE_USER { get; set; }
        public Nullable<int> iLASTMODIFIED_USER { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BLOCKED_MODULES> BLOCKED_MODULES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEACHER_PREFERRED_DAYS> TEACHER_PREFERRED_DAYS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEACHER_PREFERRED_HALLS> TEACHER_PREFERRED_HALLS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEACHER_PREFERRED_MODULES> TEACHER_PREFERRED_MODULES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEACHERS_LECTURES_LINK> TEACHERS_LECTURES_LINK { get; set; }
    }
}
