//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLink
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIMETABLE_PLANNING
    {
        public int iID_TIMETABLE_PLANNING { get; set; }
        public int iID_DAY { get; set; }
        public int iID_MODULE { get; set; }
        public int iID_SEMIGROUP { get; set; }
        public int iID_LECTURE { get; set; }
        public int iID_TEACHER { get; set; }
        public int iID_LECTURE_TYPE { get; set; }
        public int iGENERATION_NUMBER { get; set; }
        public int iID_PLANNING_TYPE { get; set; }
        public Nullable<bool> bACTIVE { get; set; }
        public Nullable<System.DateTime> dtCREATE_DATE { get; set; }
        public Nullable<System.DateTime> dtLASTMODIFIED_DATE { get; set; }
        public Nullable<int> iCREATE_USER { get; set; }
        public Nullable<int> iLASTMODIFIED_USER { get; set; }
    
        public virtual PLANNING_TYPE PLANNING_TYPE { get; set; }
    }
}
