//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLink
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEACHERS_GROUP_TYPES_PRIORITY
    {
        public int iID_TEACHER_GROUP_TYPE_PRIORITY { get; set; }
        public int iID_TEACHER { get; set; }
        public int iID_GROUP_TYPE { get; set; }
        public int iPRIORITY { get; set; }
        public bool bACTIVE { get; set; }
        public System.DateTime dtCREATE_DATE { get; set; }
        public Nullable<System.DateTime> dtLASTMODIFIED_DATE { get; set; }
        public int iCREATE_USER { get; set; }
        public Nullable<int> iLASTMODIFIED_USER { get; set; }
    
        public virtual GROUP_TYPES GROUP_TYPES { get; set; }
        public virtual TEACHERS TEACHERS { get; set; }
    }
}
