//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLink
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEACHERS_LECTURES_LINK
    {
        public int iID_TEACHERS_LECTURES_LINK { get; set; }
        public int iID_TEACHER { get; set; }
        public int iID_LECTURE { get; set; }
        public int iID_LECTURE_TYPE { get; set; }
        public int iHOURS { get; set; }
        public int iID_SEMESTER { get; set; }
        public bool bACTIVE { get; set; }
        public System.DateTime dtCREATE_DATE { get; set; }
        public Nullable<System.DateTime> dtLASTMODIFIED_DATE { get; set; }
        public int iCREATE_USER { get; set; }
        public Nullable<int> iLASTMODIFIED_USER { get; set; }
    
        public virtual LECTURE_TYPE LECTURE_TYPE { get; set; }
        public virtual LECTURES LECTURES { get; set; }
        public virtual SEMESTERS SEMESTERS { get; set; }
        public virtual TEACHERS TEACHERS { get; set; }
    }
}
