//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARPC_WPF.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BLOCKED_MODULES
    {
        public int ID_BLOCKED_MODULES { get; set; }
        public int ID_PROFESOR { get; set; }
        public int ID_MODUL { get; set; }
        public int ID_ZI { get; set; }
    
        public virtual MODULE MODULE { get; set; }
        public virtual PROFESORI PROFESORI { get; set; }
        public virtual ZILE ZILE { get; set; }
    }
}
