//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARPC_WPF.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRUPE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GRUPE()
        {
            this.LINK_MODULE_GRUPE = new HashSet<LINK_MODULE_GRUPE>();
            this.LINK_PRELEGERI_GRUPE = new HashSet<LINK_PRELEGERI_GRUPE>();
            this.SEMIGRUPEs = new HashSet<SEMIGRUPE>();
        }
    
        public int ID_GRUPA { get; set; }
        public string DENUMIRE { get; set; }
        public int NUMAR_STUDENTI { get; set; }
        public int ID_TIP_GRUPA { get; set; }
        public int AN { get; set; }
    
        public virtual TIP_GRUPA TIP_GRUPA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LINK_MODULE_GRUPE> LINK_MODULE_GRUPE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LINK_PRELEGERI_GRUPE> LINK_PRELEGERI_GRUPE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SEMIGRUPE> SEMIGRUPEs { get; set; }
    }
}
