//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARPC_WPF.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LINK_PRELEGERI_GRUPE
    {
        public int ID_LINK_PRELEGERI_GRUPE { get; set; }
        public int ID_GRUPA { get; set; }
        public int ID_PRELEGERE { get; set; }
    
        public virtual GRUPE GRUPE { get; set; }
        public virtual PRELEGERI PRELEGERI { get; set; }
    }
}
