//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARPC_WPF.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LINK_PROFESORI_PRELEGERI
    {
        public int ID_LINK_PROFESORI_PRELEGERI { get; set; }
        public int ID_PROFESOR { get; set; }
        public int ID_PRELEGERE { get; set; }
        public int ID_TIP_EXECUTIE { get; set; }
        public int NUMAR_ORE { get; set; }
    
        public virtual PRELEGERI PRELEGERI { get; set; }
        public virtual PROFESORI PROFESORI { get; set; }
        public virtual TIP_EXECUTIE TIP_EXECUTIE { get; set; }
    }
}
